trigger:
- main

stages:
- stage: Build
  jobs:
  - deployment: 'BuildAndTest'
    environment: 'Build'
    pool:
      vmImage: 'ubuntu-20.04'
    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            - task: NodeTool@0
              displayName: 'Installing Node.js'
              inputs:
                versionSpec: '10.x'
            - script: yarn install
              displayName: 'Restoring dependencies'
            - script: yarn run test
              displayName: 'Running tests'
            - task: PublishTestResults@2
              displayName: 'Publishing test results'
              inputs:
                testRunner: JUnit
                testResultsFiles: 'coverage/junit.xml'
            - task: PublishCodeCoverageResults@1
              displayName: 'Publishing code coverage'
              inputs:
                codeCoverageTool: 'Cobertura'
                summaryFileLocation: 'coverage/cobertura-coverage.xml'
            - script: yarn run build
              displayName: 'Creating artifact'
              env:
                NODE_OPTIONS: --max_old_space_size=16384
            - publish: $(System.DefaultWorkingDirectory)/dist
              displayName: 'Publishing app artifact'
              artifact: app

- stage: Staging
  jobs:
  - deployment: 'DeployStaging'
    environment: 'Staging'
    pool:
      vmImage: 'ubuntu-20.04'
    variables:
      - group: Staging
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                source: 'current'
            - task: AmazonWebServices.aws-vsts-tools.AWSCLI.AWSCLI@1
              displayName: 'Removing old package'
              inputs:
                awsCredentials: STAGING
                regionName: 'us-east-1'
                awsCommand: s3
                awsSubCommand: rm
                awsArguments: 's3://$(BUCKET_COMPANIES)/ --recursive'
                failOnStandardError: false
            - task: AmazonWebServices.aws-vsts-tools.AWSCLI.AWSCLI@1
              displayName: 'Deploying new package'
              inputs:
                awsCredentials: STAGING
                regionName: 'us-east-1'
                awsCommand: s3
                awsSubCommand: cp
                awsArguments: '$(Agent.BuildDirectory)/app s3://$(BUCKET_COMPANIES)/'
                failOnStandardError: false