import { Situation } from "./Situation";

export default class Company {
  public constructor(params: Partial<Company>) {
    this.Id = params.Id ?? 0;
    this.Name = params.Name ?? "";
    this.Image = params.Image ?? "";
    this.Sector = params.Sector ?? "";
    this.ROE = params.ROE ?? 0;
    this.ROIC = params.ROIC ?? 0;
    this.ROA = params.ROA ?? 0;
    this.NETMargin = params.NETMargin ?? 0;
    this.EBITMargin = params.EBITMargin ?? 0;
    this.EBITDAMargin = params.EBITDAMargin ?? 0;
    this.GrossMargin = params.GrossMargin ?? 0;
    this.ProfitMargin = params.ProfitMargin ?? 0;
    this.OperatingProfitMargin = params.OperatingProfitMargin ?? 0;
    this.NETDebtEBITDA = params.NETDebtEBITDA ?? 0;
    this.NETDebtEBIT = params.NETDebtEBIT ?? 0;
    this.DebtEquity = params.DebtEquity ?? 0;
    this.ShareholderEquity = params.ShareholderEquity ?? 0;
    this.CompondAnnualGrowth1Years = params.CompondAnnualGrowth1Years ?? 0;
    this.CompondAnnualGrowth3Years = params.CompondAnnualGrowth3Years ?? 0;
    this.CompondAnnualGrowth5Years = params.CompondAnnualGrowth5Years ?? 0;
    this.AvarageAnnualGrowth5Years = params.AvarageAnnualGrowth5Years ?? 0;
    this.ROESituation = params.ROESituation ?? Situation.Side;
    this.ROICSituation = params.ROICSituation ?? Situation.Side;
    this.ROASituation = params.ROASituation ?? Situation.Side;
    this.NETMarginSituation = params.NETMarginSituation ?? Situation.Side;
    this.EBITMarginSituation = params.EBITMarginSituation ?? Situation.Side;
    this.EBITDAMarginSituation = params.EBITDAMarginSituation ?? Situation.Side;
    this.GrossMarginSituation = params.GrossMarginSituation ?? Situation.Side;
    this.ProfitMarginSituation = params.ProfitMarginSituation ?? Situation.Side;
    this.OperatingProfitMarginSituation = params.OperatingProfitMarginSituation ?? Situation.Side;
    this.NETDebtEBITDASituation = params.NETDebtEBITDASituation ?? Situation.Side;
    this.NETDebtEBITSituation = params.NETDebtEBITSituation ?? Situation.Side;
    this.DebtEquitySituation = params.DebtEquitySituation ?? Situation.Side;
    this.ShareholderEquityRatioSituation = params.ShareholderEquityRatioSituation ?? Situation.Side;
    this.CompondAnnualGrowth1YearsSituation = params.CompondAnnualGrowth1YearsSituation ?? Situation.Side;
    this.CompondAnnualGrowth3YearsSituation = params.CompondAnnualGrowth3YearsSituation ?? Situation.Side;
    this.CompondAnnualGrowth5YearsSituation = params.CompondAnnualGrowth5YearsSituation ?? Situation.Side;
    this.AvarageAnnualGrowth5YearsSituation = params.AvarageAnnualGrowth5YearsSituation ?? Situation.Side;
  }

  Id: number;
  Name: string;
  Image: string;
  Sector: string;
  ROE: number;
  ROIC: number;
  ROA: number;
  NETMargin: number;
  EBITMargin: number;
  EBITDAMargin: number;
  GrossMargin: number;
  ProfitMargin: number;
  OperatingProfitMargin: number;
  NETDebtEBITDA: number;
  NETDebtEBIT: number;
  DebtEquity: number;
  ShareholderEquity: number;
  CompondAnnualGrowth1Years: number;
  CompondAnnualGrowth3Years: number;
  CompondAnnualGrowth5Years: number;
  AvarageAnnualGrowth5Years: number;
  ROESituation: Situation;
  ROICSituation: Situation;
  ROASituation: Situation;
  NETMarginSituation: Situation;
  EBITMarginSituation: Situation;
  EBITDAMarginSituation: Situation;
  GrossMarginSituation: Situation;
  ProfitMarginSituation: Situation;
  OperatingProfitMarginSituation: Situation;
  NETDebtEBITDASituation: Situation;
  NETDebtEBITSituation: Situation;
  DebtEquitySituation: Situation;
  ShareholderEquityRatioSituation: Situation;
  CompondAnnualGrowth1YearsSituation: Situation;
  CompondAnnualGrowth3YearsSituation: Situation;
  CompondAnnualGrowth5YearsSituation: Situation;
  AvarageAnnualGrowth5YearsSituation: Situation;
}