export enum Index {
  ROE = 'ROE',
  ROIC = 'ROIC',
  ROA = 'ROA',
  NETMargin = 'NET Margin',
  NETDebtEBITDA = 'NET Debt EBITDA',
  NETDebtEBIT = 'NET Debt EBIT',
  EBITMargin = 'EBIT Margin',
  EBITDAMargin = 'EBITDA Margin',
  GrossMargin = 'Gross Margin',
  ProfitMargin = 'Profit Margin',
  OperatingProfitMargin = 'Operating Profit Margin',
  DebtEquity = 'Debt Equity',
  ShareholderEquity = 'Shareholder Equity',
  CompondAnnualGrowth1Years = 'CAGR 1 Year',
  CompondAnnualGrowth3Years = 'CAGR 3 Years',
  CompondAnnualGrowth5Years = 'CAGR 5 Years',
  AvarageAnnualGrowth5Years = 'Avarage CAGR 5 Years',
}