import React, { FunctionComponent } from 'react';
import { RouteComponentProps } from '@reach/router';
import Header from '../../../components/ui/Header/Header';
import { Content } from '../../../components/ui/Content/Content';

const CompanyPage: FunctionComponent<RouteComponentProps> = () => {
  return (
    <>
      <Header fixed={false} />
      
      <Content>
      <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
        <p>Stock</p>
      </Content>
    </>
  );
};

export default CompanyPage;
